#!/bin/bash
### BEGIN INIT INFO
# Provides:          fog-service.sh
# Required-Start:    $local_fs $syslog $remote_fs
# Required-Stop:     $local_fs $syslog $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start fog service
### END INIT INFO
/opt/fog-service/control.sh $1
exit 0
