//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOG {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FOG.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} needs to perform maintenance on this computer. Please save any work and close all programs..
        /// </summary>
        internal static string DEFAULT_MESSAGE {
            get {
                return ResourceManager.GetString("DEFAULT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string HIDE {
            get {
                return ResourceManager.GetString("HIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string HOUR {
            get {
                return ResourceManager.GetString("HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string HOURS {
            get {
                return ResourceManager.GetString("HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string MINUTE {
            get {
                return ResourceManager.GetString("MINUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string MINUTES {
            get {
                return ResourceManager.GetString("MINUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postpone.
        /// </summary>
        internal static string POSTPONE {
            get {
                return ResourceManager.GetString("POSTPONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postpone for.
        /// </summary>
        internal static string POSTPONE_FOR {
            get {
                return ResourceManager.GetString("POSTPONE_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Now.
        /// </summary>
        internal static string RESTART_NOW {
            get {
                return ResourceManager.GetString("RESTART_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string SECOND {
            get {
                return ResourceManager.GetString("SECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string SECONDS {
            get {
                return ResourceManager.GetString("SECONDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown Now.
        /// </summary>
        internal static string SHUTDOWN_NOW {
            get {
                return ResourceManager.GetString("SHUTDOWN_NOW", resourceCulture);
            }
        }
    }
}
